adicionando proibiçao bot google e removendo lazy-load
cumbucadev/cinemaempoa pull request #111
Opened 2024-10-20 03:11 UTC by sylvester-96

2024-10-21 16:02 UTC, guites requested changes
Entendi o propósito do pull request, mas acho que são necessárias algumas alterações

2024-10-21 16:02 UTC, guites commented on flask_backend/templates/screening/index.html
> +<meta name="robots" content="noindex, nofollow">
Essa tag aqui eu não concordo em adicionar, pq a gente quer que a página inicial seja indexada.

- [ ] Remover meta tag da página inicial

2024-10-21 16:02 UTC, guites commented on flask_backend/static/robots.txt
> +Disallow: /screening/*/update
Gostei da ideia de usar o arquivo robots.txt!

2024-10-21 16:02 UTC, guites commented on flask_backend/__init__.py
> +    @app.route('/static/robots.txt')
Esse bloco de código é desnecessário: os arquivos na pasta `/static` ficam acessíveis automaticamente!

- [ ] Remover rota para o arquivo robots.txt

2024-10-21 16:02 UTC, guites commented on flask_backend/templates/screening/index.html
> +                 loading="lazy"
Tem um bug nessa implementação: se for a primeira imagem, você vai adicionar o atributo `alt` mesmo que ela não tenha esse valor. Repara que na linha 45 tá sendo feita uma validação (`if screening_date['image_alt']`).

Eu sugiro mudar um pouco a tua lógica:

```
{% if loop.index != 1 %}
  loading="lazy"
{% endif %}
```

Assim a gente só bota a tag `loading=lazy` quando não for o primeiro, e o resto segue tudo igual.

2024-10-21 16:02 UTC, guites commented on flask_backend/templates/screening/index.html
> -      // get the buttons screening id
algum motivo específico pra ter removido os comentários? acho que eles ajudam a entender o código

2024-10-23 13:34 UTC, sylvester-96 commented
pronto, acredito que refiz todos os pontos, quando voce analizar me diz se
ta tudo bem, mas acredito que sim


guites ***@***.***> escreveu (segunda, 21/10/2024 à(s) 17:02):

> ***@***.**** requested changes on this pull request.
>
> Entendi o propósito do pull request, mas acho que são necessárias algumas
> alterações
> ------------------------------
>
> In flask_backend/templates/screening/index.html
> <https://github.com/cumbucadev/cinemaempoa/pull/111#discussion_r1809089309>
> :
>
> > @@ -1,17 +1,13 @@
> -{% extends 'base.html' %} {% block header %}
> +{% extends 'base.html' %}
> +
> +{% block header %}
> +<meta name="robots" content="noindex, nofollow">
>
> Essa tag aqui eu não concordo em adicionar, pq a gente quer que a página
> inicial seja indexada.
>
>    - Remover meta tag da página inicial
>
> ------------------------------
>
> In flask_backend/static/robots.txt
> <https://github.com/cumbucadev/cinemaempoa/pull/111#discussion_r1809089837>
> :
>
> > @@ -0,0 +1,2 @@
> +User-agent: *
> +Disallow: /screening/*/update
>
> Gostei da ideia de usar o arquivo robots.txt!
> ------------------------------
>
> In flask_backend/__init__.py
> <https://github.com/cumbucadev/cinemaempoa/pull/111#discussion_r1809090674>
> :
>
> > @@ -49,6 +49,11 @@ def create_app(test_config=None):
>
>      app.register_blueprint(movie.bp)
>
> +    @app.route('/static/robots.txt')
>
> Esse bloco de código é desnecessário: os arquivos na pasta /static ficam
> acessíveis automaticamente!
>
>    - Remover rota para o arquivo robots.txt
>
> ------------------------------
>
> In flask_backend/templates/screening/index.html
> <https://github.com/cumbucadev/cinemaempoa/pull/111#discussion_r1809094621>
> :
>
> > -        me-sm-3" src="{{ screening_date['image'] }}" width="{{
> -        screening_date['image_display_width'] }}" height="{{screening_date['min_height']}}" loading="lazy" {% if
> -        screening_date['image_alt'] %} alt="{{ screening_date['image_alt'] }}"
> -        title="{{ screening_date['image_alt'] }}" {% endif %} /> {% else %}
> +      {% for screening_date in cinema['screening_dates'] %}
> +      {% if screening_date['image'] %}
> +      <li class="mb-5 clearfix" style="min-height: {{screening_date['min_height']}}px">
> +        <img class="img-fluid rounded float-sm-start shadow-sm mb-3 me-0 me-sm-3"
> +             src="{{ screening_date['image'] }}"
> +             width="{{ screening_date['image_display_width'] }}"
> +             height="{{ screening_date['min_height'] }}"
> +             {% if loop.index == 1 %}  <!-- Verifica se é a primeira imagem -->
> +                 alt="{{ screening_date['image_alt'] }}"
> +                 title="{{ screening_date['image_alt'] }}"
> +             {% else %}
> +                 loading="lazy"
>
> Tem um bug nessa implementação: se for a primeira imagem, você vai
> adicionar o atributo alt mesmo que ela não tenha esse valor. Repara que
> na linha 45 tá sendo feita uma validação (if screening_date['image_alt']).
>
> Eu sugiro mudar um pouco a tua lógica:
>
> {% if loop.index != 1 %}
>   loading="lazy"
> {% endif %}
>
> Assim a gente só bota a tag loading=lazy quando não for o primeiro, e o
> resto segue tudo igual.
> ------------------------------
>
> In flask_backend/templates/screening/index.html
> <https://github.com/cumbucadev/cinemaempoa/pull/111#discussion_r1809095676>
> :
>
> >      });
>    });
>
>    const deleteBtns = document.querySelectorAll('[data-function="delete"]');
>    deleteBtns.forEach((btn) => {
>      btn.addEventListener("click", () => {
> -      // get the buttons screening id
>
> algum motivo específico pra ter removido os comentários? acho que eles
> ajudam a entender o código
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cumbucadev/cinemaempoa/pull/111#pullrequestreview-2382552509>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASZUONR5JR23RRYDX2Y4YYLZ4UQR3AVCNFSM6AAAAABQICJJGWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOBSGU2TENJQHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-25 16:54 UTC, guites approved these changes
Aprovado após resolução de conflitos

2024-10-25 16:55 UTC, merged