:bug: fix query get duplicate movie_ids
cumbucadev/cinemaempoa pull request #98
Opened 2024-10-14 00:09 UTC by Gpocas

outra tentativa de resolver a issue #75, dessa vez implementei a query de forma diferente.

Como a intenção da pagina de posters é exibir apenas a url da imagem, não fazia muito sentido fazer o select em movie e depois o join com Screening sendo que todas as informações que precisamos já estão em uma unica tabela, mudei a query para realizar select diretamente na model Screening e fiz uma subquery para selecionar o maior screening_id agrupando por movie_id, fazendo com que o movie_id apareça apenas uma vez.

Essa solução não vai cobrir os casos em que exista o mesmo posters com movie_id e url diferentes,

2024-10-14 11:44 UTC, guites commented
@Gpocas ótima solução! não tive tempo de testar ainda, mas fiquei pensando se não seria melhor ignorar se os screenings pertencem a um mesmo filme ou não, e só puxar os image_url distintos.

Afinal um mesmo filme pode ter duas screenings com imagens diferentes.

Assim que eu testar aqui te dou um feedback melhor. Valeu!

2024-10-15 23:07 UTC, guites requested changes
O PR resolve o problema proposto, apenas deixei uma proposta de alteração antes de aprovar.

2024-10-15 23:07 UTC, guites commented on flask_backend/repository/movies.py
> +    )
tchê eu acho que esse `.filter` aqui pode ser removida por dois motivos:

1. Ela deixa o query meio complexo, e talvez conforme a quantidade de filmes aumente, acabe tornando o endpoint mais lento. É interessante que aqui seja o mais rápido possível pq tem impacto na fluidez da página dos posters. (admito que não sei dizer se deixa lento ou não, só tô chutando).
2. Esse filtro só permite uma screening por filme. Acontece que muitos filmes passam em mais de um cinema. Um exemplo disso é o filme "Motel Destino". Ele tem uma screening na Cinemateca Paulo Amorim, com esse poster: <https://i.ibb.co/hcBbc5N/ed26e96a9936.png> e outra screening no CineBancários, com esse poster: <https://i.ibb.co/wKBzhLD/f346e77a6585.webp>.

Eu testei aqui e essa solução, com ou sem o filtro, resolve o problema anterior onde as screenings vinham repetidas pra diferentes valores de paginação (`current_page`).

```suggestion
    query = (
        db_session.query(Screening)
        .order_by(Screening.id.desc())
    )
```

Que tal removermos o filtro?

2024-10-15 23:07 UTC, guites commented on flask_backend/routes/movie.py
> +    if lazy_loading != "1":
Boa sacada 😅 simplificou legal!

2024-10-15 23:07 UTC, guites commented on flask_backend/routes/movie.py
> +    scrennigs_list = get_paginated(page, limit, user_logged_in)
aqui tem um pequeno typo, acho que é `screenings_list`:

```suggestion
    scrennnigs_list = get_paginated(page, limit, user_logged_in)
```

(daí tem que mudar ali embaixo nos outros lugares onde é utilizado).

2024-10-21 13:18 UTC, Gpocas commented on flask_backend/repository/movies.py
> +    )
quando eu estava desenvolvendo eu até pensei nesse segundo caso que você comentou sobre o filme "Motel Destino" ter dois posters e essa modificação iria exibir apenas 1 deles, porem na estrutura do projeto atual eu não consegui pensar em nenhum outro jeito, na minha visão eu acho melhor omitir alguns filmes do que continuar repetindo, depois podemos pensar em uma solução mais robusta.

2024-10-25 16:27 UTC, guites commented on flask_backend/routes/movie.py
> +    scrennigs_list = get_paginated(page, limit, user_logged_in)
Ajustei junto com o merge

2024-10-25 16:27 UTC, guites commented on flask_backend/repository/movies.py
> +    )
Opa, não sei se ficou claro, mas eu removi só a parte do `func.max(Screening.id)` e reparei que a solução seguiu funcionando!

2024-10-25 16:28 UTC, merged